version: '3.8'
services:
  backend:
    build: ./back
    container_name: flashify-backend
    env_file:
      - ./back/.env
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./back/app:/app/app
    restart: always
  frontend:
    build: ./front
    container_name: flashify-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - backend
    restart: always
