services:
  backend:
    build: ./back
    container_name: flashify-backend
    env_file:
      - ./back/.env
    ports:
      - "9000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./back/app:/app/app
    restart: always
  frontend:
    build: ./front
    container_name: flashify-frontend
    env_file:
      - ./front/.env
    ports:
      - "4000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
