services:
  db:
    image: postgres:15
    container_name: flashify-db
    env_file:
      - ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashify -d flashify"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal-net

  redis:
    image: redis:7-alpine
    container_name: flashify-redis
    restart: always
    networks:
      - internal-net

  backend:
    build: ./back
    container_name: flashify-backend
    env_file:
      - ./back/.env
    volumes:
      - ./uploads:/app/uploads
      - ./back/gcp-credentials.json:/app/gcp-credentials.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    networks:
      - proxy-net
      - internal-net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  celery-worker:
    build: ./back
    container_name: flashify-worker
    command: celery -A app.worker worker --loglevel=info
    env_file:
      - ./back/.env
    volumes:
      - ./uploads:/app/uploads
      - ./back/gcp-credentials.json:/app/gcp-credentials.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    networks:
      - proxy-net
      - internal-net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  celery-beat:
    build: ./back
    container_name: flashify-beat
    command: celery -A app.worker beat --loglevel=info
    env_file:
      - ./back/.env
    volumes:
      - ./uploads:/app/uploads
      - ./back/gcp-credentials.json:/app/gcp-credentials.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    networks:
      - internal-net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
    container_name: flashify-frontend
    env_file:
      - ./front/.env
    depends_on:
      - backend
    restart: always
    networks:
      - proxy-net
    dns:
      - 8.8.8.8 
      - 1.1.1.1  

volumes:
  postgres_data: {}

networks:
  proxy-net:
    external: true
  internal-net:
    internal: true