services:
  db:
    image: postgres:15
    container_name: flashify-db
    environment:
      POSTGRES_USER: flashify
      POSTGRES_PASSWORD: flashify
      POSTGRES_DB: flashify
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: flashify-redis
    ports:
      - "6380:6379"
    restart: always

  backend:
    build: ./back
    container_name: flashify-backend
    env_file:
      - ./back/.env
    ports:
      - "9000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./back/app:/app/app
    depends_on:
      - db
      - redis
    restart: always
  celery-worker:
    build: ./back
    container_name: flashify-worker
    command: celery -A app.worker worker --loglevel=info
    env_file:
      - ./back/.env
    volumes:
      - ./uploads:/app/uploads
      - ./back/app:/app/app
    depends_on:
      - db
      - redis
    restart: always

  frontend:
    build: ./front
    container_name: flashify-frontend
    env_file:
      - ./front/.env
    ports:
      - "4000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
