# docker-compose.yml
services:
  db:
    image: postgres:14-alpine
    container_name: flashify_db
    environment:
      - POSTGRES_USER=flashify_user
      - POSTGRES_PASSWORD=flashify_password
      - POSTGRES_DB=flashify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # NOVO SERVIÇO REDIS
  redis:
    image: redis:7-alpine
    container_name: flashify_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: